language: cpp
compiler:
 - gcc
 - clang
env:
 - CONFIG=debug
 - CONFIG=debug RAGEL=ragel
 - CONFIG=debug ZLIB=disable_zlib
 - CONFIG=debug QT5=qt5
 - CONFIG=release
 - CONFIG=release QT5=qt5
before_install:
 - sudo apt-get update -qq
 - bash -c "if [[ -n \"${RAGEL}\" ]]; then sudo apt-get install -qq ragel; fi"
 - bash -c "if [[ -z \"${ZLIB}\" ]]; then sudo apt-get install -qq zlib1g-dev; fi"
 - bash -c "if [[ -z \"${QT5}\" ]]; then sudo apt-get install -qq libqt4-dev qt4-dev-tools libqtwebkit-dev libqt4-sql-sqlite; else sudo apt-add-repository -y ppa:beineri/opt-qt502; sudo apt-add-repository -y ppa:leppa/backports; sudo apt-get update -qq; sudo apt-get install -qq qt5-meta-minimal qttools libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev; fi"
 - sudo apt-get install -qq xvfb xauth cmake
 - bash -c "cmake --version"
script: bash -c "mkdir _build; cd _build; cmake -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=$CONFIG ${QT5:+-DCMAKE_PREFIX_PATH=/opt/qt5/lib/cmake} ${QT5:+-DWITH_QT5=1} ${RAGEL:+-DWITH_RAGEL=1} ${ZLIB:+-DWITHOUT_ZLIB=1} -DCMAKE_INSTALL_PREFIX=/usr .. && make VERBOSE=1 -j4 && xvfb-run -a ctest -j 4 --output-on-failure && sudo make install"
notifications:
 irc:
  channels:
   - "chat.freenode.net#trojita"
  on_success: change
  use_notice: true
